version: "3.7"

services:
  my-node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      NODE_ENV: production
    command: ts-dev-node index.ts
