version: "3.7"

services:
  my-ts-node-app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    labels:
      version: "1.0.0"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    depends_on:
      - mysql
    command: bash -c "npx prisma generate && npx prisma migrate dev --name init"
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3310:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
